### ISSUE TITLE
cannot import name 'LocalEntryNotFoundError' 

### ISSUE THREAD

**Issue by wfq1971** [okaris/omni-zero#13]
ImportError: cannot import name 'LocalEntryNotFoundError' from 'huggingface_hub.errors' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/errors.py)

**Comment by okaris** [comment]
Please make sure you install the requirements as insteucted in the readme

**Comment by wfq1971** [comment]
diffusion_pytorch_model.safetensors: 100% 10.3G/10.3G [04:17<00:00, 39.9MB/s]
Fetching 20 files: 100% 20/20 [04:18<00:00, 12.93s/it]
Loading pipeline components...: 100% 7/7 [00:03<00:00,  1.91it/s]
Traceback (most recent call last):
  File "/content/omni-zero/app.py", line 52, in <module>
    pipeline = OmniZeroPipeline.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 972, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "/content/omni-zero/pipeline.py", line 315, in __init__
    self.register_modules(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 159, in register_modules
    library, class_name = _fetch_class_library_tuple(module)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_loading_utils.py", line 733, in _fetch_class_library_tuple
    not_compiled_module = _unwrap_model(module)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_loading_utils.py", line 236, in _unwrap_model
    from peft import PeftModel
  File "/usr/local/lib/python3.10/dist-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/usr/local/lib/python3.10/dist-packages/peft/auto.py", line 31, in <module>
    from .config import PeftConfig
  File "/usr/local/lib/python3.10/dist-packages/peft/config.py", line 24, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/__init__.py", line 22, in <module>
    from .loftq_utils import replace_lora_weights_loftq
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/loftq_utils.py", line 26, in <module>
    from huggingface_hub.errors import HFValidationError, LocalEntryNotFoundError
ImportError: cannot import name 'LocalEntryNotFoundError' from 'huggingface_hub.errors' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/errors.py)

**Comment by wfq1971** [comment]
of course,i have this sentence pip install -r requirements.txt

**Comment by wfq1971** [comment]
i think you need !pip install huggingface-hub==0.25.0

**Comment by wfq1971** [comment]
solve,please add this :pip install peft==0.11.0 in requirement
